import{r as n,M as S,j as p,u as P,P as T,a as _,b as $,L as D,m as A}from"../assets/proxy.js";class K extends n.Component{getSnapshotBeforeUpdate(i){const e=this.props.childRef.current;if(e&&i.isPresent&&!this.props.isPresent){const t=this.props.sizeRef.current;t.height=e.offsetHeight||0,t.width=e.offsetWidth||0,t.top=e.offsetTop,t.left=e.offsetLeft}return null}componentDidUpdate(){}render(){return this.props.children}}function N({children:s,isPresent:i}){const e=n.useId(),t=n.useRef(null),f=n.useRef({width:0,height:0,top:0,left:0}),{nonce:d}=n.useContext(S);return n.useInsertionEffect(()=>{const{width:u,height:o,top:h,left:r}=f.current;if(i||!t.current||!u||!o)return;t.current.dataset.motionPopId=e;const c=document.createElement("style");return d&&(c.nonce=d),document.head.appendChild(c),c.sheet&&c.sheet.insertRule(`
          [data-motion-pop-id="${e}"] {
            position: absolute !important;
            width: ${u}px !important;
            height: ${o}px !important;
            top: ${h}px !important;
            left: ${r}px !important;
          }
        `),()=>{document.head.removeChild(c)}},[i]),p.jsx(K,{isPresent:i,childRef:t,sizeRef:f,children:n.cloneElement(s,{ref:t})})}const O=({children:s,initial:i,isPresent:e,onExitComplete:t,custom:f,presenceAffectsLayout:d,mode:u})=>{const o=P(U),h=n.useId(),r=n.useCallback(m=>{o.set(m,!0);for(const v of o.values())if(!v)return;t&&t()},[o,t]),c=n.useMemo(()=>({id:h,initial:i,isPresent:e,custom:f,onExitComplete:r,register:m=>(o.set(m,!1),()=>o.delete(m))}),d?[Math.random(),r]:[e,r]);return n.useMemo(()=>{o.forEach((m,v)=>o.set(v,!1))},[e]),n.useEffect(()=>{!e&&!o.size&&t&&t()},[e]),u==="popLayout"&&(s=p.jsx(N,{isPresent:e,children:s})),p.jsx(T.Provider,{value:c,children:s})};function U(){return new Map}const g=s=>s.key||"";function j(s){const i=[];return n.Children.forEach(s,e=>{n.isValidElement(e)&&i.push(e)}),i}const k=({children:s,custom:i,initial:e=!0,onExitComplete:t,presenceAffectsLayout:f=!0,mode:d="sync",propagate:u=!1})=>{const[o,h]=_(u),r=n.useMemo(()=>j(s),[s]),c=u&&!o?[]:r.map(g),m=n.useRef(!0),v=n.useRef(r),y=P(()=>new Map),[L,b]=n.useState(r),[x,R]=n.useState(r);$(()=>{m.current=!1,v.current=r;for(let a=0;a<x.length;a++){const l=g(x[a]);c.includes(l)?y.delete(l):y.get(l)!==!0&&y.set(l,!1)}},[x,c.length,c.join("-")]);const w=[];if(r!==L){let a=[...r];for(let l=0;l<x.length;l++){const C=x[l],M=g(C);c.includes(M)||(a.splice(l,0,C),w.push(C))}d==="wait"&&w.length&&(a=w),R(j(a)),b(r);return}const{forceRender:E}=n.useContext(D);return p.jsx(p.Fragment,{children:x.map(a=>{const l=g(a),C=u&&!o?!1:r===x||c.includes(l),M=()=>{if(y.has(l))y.set(l,!0);else return;let z=!0;y.forEach(I=>{I||(z=!1)}),z&&(E==null||E(),R(v.current),u&&(h==null||h()),t&&t())};return p.jsx(O,{isPresent:C,initial:!m.current||e?void 0:!1,custom:C?void 0:i,presenceAffectsLayout:f,mode:d,onExitComplete:C?void 0:M,children:a},l)})})};function F(){const[s,i]=n.useState([]);return n.useEffect(()=>{let e=0,t=0;const f=d=>{const u=Date.now();if(u-t<30)return;t=u;const o={id:e++,x:d.clientX,y:d.clientY,size:Math.random()*4+2};i(h=>[...h.slice(-15),o])};return window.addEventListener("mousemove",f),()=>window.removeEventListener("mousemove",f)},[]),n.useEffect(()=>{if(s.length===0)return;const e=setTimeout(()=>{i(t=>t.slice(1))},400);return()=>clearTimeout(e)},[s]),p.jsx("div",{className:"pointer-events-none fixed inset-0 z-[9999] overflow-hidden",children:p.jsx(k,{children:s.map(e=>p.jsx(A.div,{initial:{opacity:.8,scale:1,x:e.x,y:e.y},animate:{opacity:0,scale:0,y:e.y+40,x:e.x+(Math.random()*40-20)},exit:{opacity:0},transition:{duration:.6,ease:"easeOut"},className:"absolute rounded-full bg-spell shadow-[0_0_8px_2px_rgba(45,212,191,0.6)]",style:{width:e.size,height:e.size,left:-e.size/2,top:-e.size/2}},e.id))})})}export{k as A,F as C};
